#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tanzu-sync-secrets
  namespace: tanzu-sync
  annotations:
    kapp.k14s.io/change-group: eso/secretstore
    kapp.k14s.io/change-rule.0: "upsert after upserting eso/install"
    kapp.k14s.io/change-rule.1: "delete before deleting eso/install"
spec:
  provider:
    azurekv:
      tenantId: #@ data.values.secrets.eso.azurekv.tenantId
      vaultUrl: #@ data.values.secrets.eso.azurekv.vaultUrl
      authSecretRef:
        clientId:
          name: #@ data.values.secrets.eso.azurekv.authSecretRef.clientId.name
          key: #@ data.values.secrets.eso.azurekv.authSecretRef.clientId.key
        clientSecret:
          name: #@ data.values.secrets.eso.azurekv.authSecretRef.clientSecret.name
          key: #@ data.values.secrets.eso.azurekv.authSecretRef.clientSecret.key
