#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tap-install-secrets
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: eso/secretstore
spec:
  provider:
    azurekv:
      tenantId: #@ data.values.tap_install.secrets.eso.azurekv.tenantId
      vaultUrl: #@ data.values.tap_install.secrets.eso.azurekv.vaultUrl
      authSecretRef:
        clientId:
          name: #@ data.values.tap_install.secrets.eso.azurekv.authSecretRef.clientId.name
          key: #@ data.values.tap_install.secrets.eso.azurekv.authSecretRef.clientId.key
        clientSecret:
          name: #@ data.values.tap_install.secrets.eso.azurekv.authSecretRef.clientSecret.name
          key: #@ data.values.tap_install.secrets.eso.azurekv.authSecretRef.clientSecret.key